#!/bin/sh /etc/rc.common

START=99  # Service startup order
STOP=99  # Service stop order
USE_PROCD=1
Name=onewifi_em_agent
VETH_AGENT_PEER="eth1_virt_peer"
BRIDGE_NAME="br-lan"
DELAY_BEFORE_AGENT_START=30 #Delay in seconds

# Process 1 configuration
PROG1="/usr/bin/ieee1905"
PIDFILE1="/tmp/ieee1905_agent.pid"
ARGS1="-f ieee1905::al_sap=trace,ieee1905::cmdu_handler=trace,ieee1905::cmdu_proxy=trace,ieee1905::cmdu_observer=trace -i eth1_virt_peer"

# Process 2 configuration
PROG2="/usr/bin/onewifi_em_agent"
PIDFILE2="/tmp/em_agent.pid"

start_service() {
    echo "Starting em_agent service..." >> /tmp/em_agent_log.txt
    # Run setup_veth_for_em_agent.sh only if virtual ethernet interface
    # is not created
    if [ ! -e "/sys/class/net/$VETH_AGENT_PEER/address" ]; then
        echo "Running setup_veth_for_em_agent.sh..." >> /tmp/em_agent_log.txt
        cd /banana-pi
        ./setup_veth_for_em_agent.sh $BRIDGE_NAME >> /tmp/em_agent_log.txt
    fi

    # Use procd to manage the ieee1905 process and em_controller process
    procd_open_instance "ieee1905_agent"
    procd_set_param command $PROG1 $ARGS1 # Command with arguments
    procd_set_param respawn 25 10 10  # Automatically restart if down
    procd_set_param limits core="unlimited"
    procd_set_param limits stack="unlimited"
    procd_set_param stdout 1 # forward stdout of the command to logd
    procd_set_param stderr 1 # same for stderr
    procd_set_param pidfile "$PIDFILE1"
    procd_close_instance

    procd_open_instance "onewifi_em_agent"
    procd_set_param command $PROG2  # Command with arguments
    procd_set_param respawn 50 10 10  # Automatically restart if down
    procd_set_param limits core="unlimited"
    procd_set_param limits stack="unlimited"
    procd_set_param stdout 1 # forward stdout of the command to logd
    procd_set_param stderr 1 # same for stderr
    procd_set_param pidfile "$PIDFILE2"
    procd_set_param delay DELAY_BEFORE_AGENT_START # Wait before starting the command
    procd_close_instance
}

stop_service() {
    echo "Stopping onewifi_em_agent service..." >> /tmp/em_agent_log.txt
    # Stop the main process if it is running
    if [ -f $PIDFILE2 ]; then
        kill -9 "$(cat $PIDFILE2)"  # Kill the process
        rm -f $PIDFILE2         # Remove the PID file
    fi
    echo "Stopping ieee1905 service..." >> /tmp/em_agent_log.txt
    # Stop the main process if it is running
    if [ -f $PIDFILE1 ]; then
        kill -9 "$(cat $PIDFILE1)"  # Kill the process
        rm -f $PIDFILE1         # Remove the PID file
    fi
}

restart_service() {
    echo "Restart triggered for em_agent service..."
    stop
    start
}

reload_service() {
    echo "Reload triggered for em_agent service..."
    stop
    start
}
